### ISSUE TITLE
PopperArrow must be within Popper

### ISSUE THREAD

**Issue by HarunKilic** [dohomi/tamagui-kitchen-sink#16] opened 2023-04-08 16:50 UTC
Using LmAutocomplete in Expo leads to this error: 

```
Error: `PopperArrow` must be used within `Popper`

This error is located at:
    in PopperArrow2 (created by PopoverArrow)
    in PopoverArrow (created by LmPopover)
``` 
    
    Using version: `0.12.13`

**Comment by dohomi** [comment] 2023-04-11 01:28
This might be some error when the LmAutocomplete changes to sheet? I currently suffer from the iOS XCode issue that locally my entire expo dev is not starting at all.. Will try to solve this asap

**Comment by HarunKilic** [comment] 2023-04-11 09:33
This happens as soon as the component is created

**Comment by dohomi** [comment] 2023-04-13 06:15
@HarunKilic can you check out 0.14.0? I reworked date and autocomplete components and also fixed a few other minor bugs with Expo. Hopefully now the app compiles correctly

**Comment by HarunKilic** [comment] 2023-04-13 12:32
Unfortunately same error

**Comment by HarunKilic** [comment] 2023-04-14 20:07
I've added minimal reproduction of the error: https://github.com/HarunKilic/tamagui-extras-repro

**Comment by dohomi** [comment] 2023-04-18 13:13
@HarunKilic can you see if the issue is solved with the new `@tamagui-extras/form`?

**Comment by dohomi** [comment] 2023-05-11 00:58
will close this for now feel free to re-open

**Closed as completed by dohomi** 2023-05-11 00:58 UTC
