### ISSUE TITLE
onChange doesn't get triggered for LmDatepicker on iOS and Android

### ISSUE THREAD

**Issue by mohamadchehab** [dohomi/tamagui-kitchen-sink#41] opened 2023-12-21 04:40 UTC
When using LmDatepicker on Web, the onChange function gets triggered which allows me to use a setDate function and update the date. However, on iOS and Android, this function doesn't get triggered so the component is not usable. Please let me know if any fix is available soon. Thanls.

**Comment by dohomi** [comment] 2023-12-21 16:59
this issue is a duplicate of https://github.com/dohomi/tamagui-kitchen-sink/issues/39 and it should be resolved in the most recent version?

**Comment by mohamadchehab** [comment] 2023-12-21 17:35
Hi,
I was able to resolve the issue by adding a add a
useEffect(()=>{onChange(state),[state]) to the LmDatepicker.native.js file
Thanks for getting back to me
Mohamad

**Comment by dohomi** [comment] 2023-12-22 08:48
@mohamadchehab thats part of the latest release already: https://github.com/dohomi/tamagui-kitchen-sink/blob/master/packages/date/src/datepicker/LmDatepicker.native.tsx#L36

**Closed as completed by dohomi** 2023-12-22 08:48 UTC
